import 'package:json_serializer/json_serializer.dart';

part 'person.g.dart'; // This will be generated by json_serializable

@JsonSerializable()
class Person {
  final int? id; // Assuming Neo4j assigns IDs
  final String name;
  final ContactInfo contactInfo;
  final List<String> relationshipTypes; // List of relationship types (friend, family, etc.)

  Person({
    this.id,
    required this.name,
    required this.contactInfo,
    this.relationshipTypes = const [],
  });

  factory Person.fromJson(Map<String, dynamic> json) => _$PersonFromJson(json);
  Map<String, dynamic> toJson() => _$PersonToJson(this);
}

@JsonSerializable()
class ContactInfo {
  final String? email;
  final String? phoneNumber;
  // Add more contact fields as needed

  ContactInfo({
    this.email,
    this.phoneNumber,
  });

  factory ContactInfo.fromJson(Map<String, dynamic> json) => _$ContactInfoFromJson(json);
  Map<String, dynamic> toJson() => _$ContactInfoToJson(this);
}